### ISSUE TITLE
macOS Support on `parseSourceFolderArgument` function

### ISSUE THREAD

**Issue by bic4907** [chatgpt4pcg/chatgpt4pcg-node#1]
I got a message "Insufficient parameters to work with" when I run `npm start -s "./competition"` in the command line.

The `parseSourceFolderArgument` function in `chatgpt4pcg-node` package is not working in macOS.
I guess the function is implemented in win32; not supporting in 'darwin' platform.

```bash
(base)  inchang  ~/Desktop/text-to-xml-converter-script   main ±  npm start -s "./competition"
{ _: [ './competition' ] }
Insufficient parameters to work with.
```

I temporarily resolved this issue through editing the package source code into below.
Due to the value of `-s` is stored in `__`, the code may changed to consider both platforms.

```node
function parseSourceFolderArgument() {
    const args = (0, minimist_1.default)(process.argv.slice(2));
    console.log(args)
    const argv = process.platform === 'win32' || process.platform == 'darwin'  ? args['_'] : args['s'];
    if (argv === undefined) {
        throw Error('Insufficient parameters to work with.');
    }
    return path_1.default.posix.resolve(argv + '/');
}
```

**Comment by Pittawat2542** [comment]
Hi! Thank you for reporting the issue. This appears to be related to the `chatgpt4pcg-node` package and not specifically to this conversation script. Therefore, I'll move this issue to the appropriate repository.

Indeed, this seems to be a bug on macOS as I can also reproduce this issue when using `npm`. Strangely, this behavior does not occur with other package managers like `pnpm`. It seems like each package manager handles this differently on each OS.

**Comment by bic4907** [comment]
Thank you for your comment.  
I'd appreciate it to update this issue on next update :)
